config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'items#index'
  resources :items do
    resources :orders, only:[:index, :create]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  attr_accessor :token

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  belongs_to :item_purchase
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  class Article < ApplicationRecord
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :category

    # 空の投稿を保存できないようにする
    validates :prefecture, :price, :scheduled_delivery, :shipping_fee_status, :category, :sales_status, presence: true

    # ジャンルの選択が「--」の時は保存できないようにする
    validates :category, numericality: { other_than: 1 }
    validates :prefecture, numericality: { other_than: 1 }
    validates :scheduled_delivery, numericality: { other_than: 1 }
    validates :shipping_fee_status, numericality: { other_than: 1 }
    validates :sales_status, numericality: { other_than: 1 }
  end
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '居酒屋' },
    { id: 3, name: 'バル' },
    { id: 4, name: 'ビストロ' },
    { id: 5, name: 'レストラン' },
    { id: 6, name: 'グランメゾン' },
    { id: 7, name: 'カフェ' },
    { id: 8, name: 'その他' }
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :scheduled_delivery
  belongs_to_active_hash :shipping_fee_status
  belongs_to_active_hash :sales_status

  belongs_to :user
  has_one :item_purchase
  has_one_attached :image

  validates :name, presence: true
  validates :image, presence: true
  validates_inclusion_of :price, in: 300...9_999_999
  validates :info, presence: true
  with_options presence: true, numericality: { other_than: 1 } do
    validates :category_id
    validates :prefecture_id
    validates :scheduled_delivery_id
    validates :shipping_fee_status_id
    validates :sales_status_id
  end
end

app/models/item_purchase.rb
class ItemPurchase < ApplicationRecord
  belongs_to :item
  belongs_to :user
  has_one :address
end

app/models/item_purchase_address.rb
class ItemPurchaseAddress
  include ActiveModel::Model
  attr_accessor :user_id, :item_id, :name, :phone_number, :time, :day, :building

  validates :name, presence: true
  validates :phone_number, format: { with: /\A\d{10,11}\z/ }
  validates :time, presence: true
  validates :day, presence: true
  validates :building, presence: true
  validates :user_id, presence: true
  validates :item_id, presence: true


  def save
    item_purchase = ItemPurchase.create(item_id: item_id, user_id: user_id)
    Address.create(item_purchase_id: item_purchase.id, name: name, phone_number: phone_number, time: time, day: day, building: building )
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ランチのみ(午前中~夕方まで)' },
    { id: 3, name: 'ランチ・ディナー(午前中~午後23時頃まで)' },
    { id: 4, name: 'ディナーのみ(夕方~午後23時頃まで)' },
    { id: 5, name: '24時間営業' },
    { id: 6, name: 'その他' }
  ]
end

app/models/sales_status.rb
class SalesStatus < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '1人' },
    { id: 3, name: '2人' },
    { id: 4, name: '3人~4人' },
    { id: 5, name: '5人~6人' },
    { id: 6, name: '7人~8人' },
    { id: 7, name: '10人以上' }

  ]
end

app/models/scheduled_delivery.rb
class ScheduledDelivery < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '新店(オープンから半年以内)' },
    { id: 3, name: '老舗' },
    { id: 4, name: '独特な営業スタイル' },
    { id: 5, name: '専門料理' },
    { id: 6, name: 'ドリンクメニューが豊富' },
    { id: 7, name: '破格な安さ' },
    { id: 8, name: 'オシャレ' },
    { id: 9, name: '創作アレンジ料理が豊富' },
    { id: 10, name: '雰囲気のある内装' }

  ]
end

app/models/shipping_fee_status.rb
class ShippingFeeStatus < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '田端駅' },
    { id: 3, name: '西日暮里駅' },
    { id: 4, name: '日暮里駅' },
    { id: 5, name: '鷲谷駅' },
    { id: 6, name: '上野駅' },
    { id: 7, name: '御徒町駅' },
    { id: 8, name: '秋葉原駅' },
    { id: 9, name: '神田駅' },
    { id: 10, name: '東京駅' },
    { id: 11, name: '有楽町駅' },
    { id: 12, name: '新橋駅' },
    { id: 13, name: '浜松町駅' },
    { id: 14, name: '田町駅' },
    { id: 15, name: '品川駅' },
    { id: 16, name: '大崎駅' },
    { id: 17, name: '五反田駅' },
    { id: 18, name: '目黒駅' },
    { id: 19, name: '恵比寿駅' },
    { id: 20, name: '渋谷駅' },
    { id: 21, name: '原宿駅' },
    { id: 22, name: '代々木駅' },
    { id: 23, name: '新宿駅' },
    { id: 24, name: '新大久保駅' },
    { id: 25, name: '高田馬場駅' },
    { id: 26, name: '目白駅' },
    { id: 27, name: '池袋駅' },
    { id: 28, name: '大塚駅' },
    { id: 29, name: '巣鴨駅' },
    { id: 30, name: '駒込駅' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :item_purchases

  validates :nickname, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }
  validates :email, format: { with: /@.+/ }
  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ } do
    validates :first_name
    validates :last_name
  end
  with_options presence: true, format: { with: /\A[ァ-ン]+\z/ } do
    validates :first_name_kana
    validates :last_name_kana
  end
  validates :birth_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :basic_auth

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :encrypted_password, :first_name, :last_name, :first_name_kana, :last_name_kana, :birth_date])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_item, only: [:edit, :show, :update, :destroy]

  def index
    @items = Item.all.order(created_at: :DESC)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.valid?
      @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:scheduled_delivery_id, :category_id, :prefecture_id, :shipping_fee_status_id, :sales_status_id, :price, :name, :info, :image).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_item, only: [:index, :create]
  before_action :move_to_root, only: [:index]

  def index
    if @item.item_purchase.present?
      redirect_to root_path
    else
      @item_purchase_address = ItemPurchaseAddress.new
    end
  end

  def create
    @item_purchase_address = ItemPurchaseAddress.new(item_purchase_address)

    if @item_purchase_address.valid?
      @item_purchase_address.save
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def item_purchase_address
    params.permit(:name, :phone_number, :time, :day, :building, :item_id).merge(user_id: current_user.id)
  end

  

  def set_item
    @item = Item.find(params[:item_id])
  end

  def move_to_root
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    if user_signed_in? && current_user.id == @item.user_id 
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変える予約管理アプリ
    </h2>
    <p class='service-explain'>
      YOYAKUはだれでもかんたんに出店・予約できる
    </p>
    <p class='service-explain'>
      予約管理アプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      YOYAKUが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag 'IMG_0584.JPG' , size: '200x200' ,class: "list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに予約
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に予約できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag 'IMG_0583.JPG' , size: '200x200' ,class: "list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>簡単</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、予約、出店もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag 'IMG_0585.JPG' , size: '200x200' ,class: "list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          充実！
          <span class='reason-list-blue-text'>ポイントでお得に利用</span>
        </h3>
        <p class='reason-list-description'>
          最大30%offでお得にお食事が楽しめる！
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      YOYAKUは、予約管理アプリで最も人気。
    </p>
    <p class='ad-explain'>
      出店数・予約数も業界最多です！
    </p>
    <p class='ad-explain'>
      なかなか予約の取れないあのお店を利用できるかも
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      YOYAKUの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          すぐ見つかる！
        </h3>
        <p class='feature-list-description'>
          簡単操作で最速予約可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          電話要らず！
        </h3>
        <p class='feature-list-description'>
          場所を選ばず柔軟に予約ができます！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          ポイント還元！
        </h3>
        <p class='feature-list-description'>
          利用すればするほどお得にご利用できます！
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>注目のお店</h2>
    <%= link_to '新規投稿店舗', new_item_path, class: "subtitle" %>
    <ul class='item-lists'>
      <% if @items.length != 0 %>
      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <% @items.each do |item|%>
      <li class='list'>
        <%= link_to item_path(item) do %>
        <div class='item-img-content'>
          <%= image_tag item.image,class: "item-img" %>
          <%# 商品が売れていればsold outを表示しましょう %>
          <% if item.item_purchase.present? %>
          <div class='sold-out'>
            <span>予約で一杯です!!</span>
          </div>
          <% end %>
          <%# //商品が売れていればsold outを表示しましょう %>
        
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
          <% end %>
        <% end %>
      </li>
      <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <% else %>
      <%# 商品がない場合のダミー %>
      <%# 商品がある場合は表示されないようにしましょう %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            商品を出品してね！
          </h3>
          <div class='item-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <%# //商品がある場合は表示されないようにしましょう %>
      <% end %>
      <%# /商品がない場合のダミー %>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<div class='purchase-btn'>
  <span class='purchase-btn-text'>出店する</span>
  <%# <%=form_with model: @item, local: true do |f|%> 
  <a href="/items/new">
    <%= image_tag 'IMG_0581.jpeg' , size: '185x50' ,class: "purchase-btn-icon" %>
  </a>
</div>
<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @item.image ,class:"item-box-img" %>
      <%# 商品が売れている場合は、sold outを表示しましょう %>
      <div class='sold-out'>
      <% if @item.item_purchase.present? %>
        <span>Sold Out!!</span>
      <% end %>
      </div>
      <%# //商品が売れている場合は、sold outを表示しましょう %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= @item.price %>円
      </span>
      <span class="item-postage">
        (税込) 送料込み
      </span>
    </div>

    <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
    <% if user_signed_in? && current_user.id == @item.user_id %>
    <%= link_to '店舗の編集',  edit_item_path, method: :get, class: "item-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', item_path, method: :delete, class:'item-destroy' %>
    <% else %>
    <%# 商品が売れていない場合はこちらを表示しましょう %>
    <% if user_signed_in? %>
    <% if @item.item_purchase.present? %>
    <% else %>
    <%= link_to '予約画面に進む',item_orders_path(@item.id),class:"item-red-btn"%>
    <% end %>
    <%# //商品が売れていない場合はこちらを表示しましょう %>
    <% end %>
    

    <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
    <% end %>
    <div class="item-explain-box">
      <span><%= @item.info %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">店舗名</th>
          <td class="detail-value"><%= @item.name %></td>
        </tr>
        <tr>
          <th class="detail-item">店舗形態</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">予約最大人数</th>
          <td class="detail-value"><%= @item.sales_status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">最寄駅</th>
          <td class="detail-value"><%= @item.shipping_fee_status.name%></td>
        </tr>
        <tr>
          <th class="detail-item">営業時間</th>
          <td class="detail-value"><%= @item.prefecture.name%></td>
        </tr>
        <tr>
          <th class="detail-item">店舗の特徴</th>
          <td class="detail-value"><%= @item.scheduled_delivery.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class='another-item'><%= @item.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>YOYAKU</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/orders/index.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      店舗情報の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @item.image, class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h1 class='buy-item-text'>
          <%= @item.name %>
        </h1>
        <div class='buy-item-price'>
          <p class='item-price-text'><%=@item.shipping_fee_status.name%></p>
          <p class='item-price-sub-text'>（最寄駅）</p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        客単価
      </h1>
      <p class='item-payment-price'>
        約¥<%= @item.price %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with  url: item_orders_path , id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>

    <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        『店舗の住所・最寄からのアクセス・その他』
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text"></label>
          <span class="indispensable">下記を必ずご確認下さい↓</span>
        </div>
      <p class='info-input-haedline'>
        <%=@item.info%>
      </p>
         <%# 消すとまずいやつ %>
          <%# 消すとまずいやつ %>
        <div class='available-card'>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text"></label>
          
        </div>
        <div class='input-expiration-date-wrap'>
          <%# 消すとまずいやつ %>
          <%# 消すとまずいやつ %>
          <p></p>
          <%# 消すとまずいやつ %>
          <%# 消すとまずいやつ %>
          <p></p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text"></label>
        </div>


      </div>
    </div>
    <%# /カード情報の入力 %>
    
    <%# 予約者の情報記入欄 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        ご予約者様記入欄
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">予約者様のお名前</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :name, class:"input-default", id:"postal-code", placeholder:"例）山田太郎", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">予約者様の電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :phone_number, class:"input-default", id:"postal-code", placeholder:"例）09012341234", maxlength:"11" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">ご予約日時</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :day, class:"input-default", id:"city", placeholder:"例）1月1日"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">ご予約時間</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :time, class:"input-default", id:"addresses", placeholder:"例）19時30分"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">お連れ様との関係性</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :building, class:"input-default", id:"building", placeholder:"例）恋人"%>
      </div>
    </div>
    <%# /配送先の入力 %>
    <div class='buy-btn'>
      <%= f.submit "予約確定",class:"buy-red-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるYOYAKU
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>YOYAKUについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'YOYAKU利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>YOYAKUを見る</h2>
      <ul>
        <li><%= link_to '店舗一覧', "#", class: "footer-link" %></li>
        <li><%= link_to '新店舗一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>YOYAKUについて</h2>
      <ul>
        <li><%= link_to 'YOYAKUガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'YOYAKUロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("IMG_0581.jpeg", class:"logo-white"), "#" %>
  <p>© YOYAKU</p>
</div>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>YOYAKU利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "IMG_0581.jpeg", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("IMG_0581.jpeg", class:"second-logo"), "/" %>
</header>